/* newtab.svelte generated by Svelte v3.48.0 */
import {
	SvelteComponentDev,
	add_location,
	append_dev,
	append_styles,
	attr_dev,
	detach_dev,
	dispatch_dev,
	element,
	init,
	insert_dev,
	noop,
	safe_not_equal,
	validate_slots
} from "nereid://.svelte/internal/index.mjs";

const file = "newtab.svelte";

function add_css(target) {
	append_styles(target, "svelte-1wkv2w3", ".app.svelte-1wkv2w3{position:fixed;width:100%;height:100%;backdrop-filter:blur(3px)}h2.svelte-1wkv2w3{margin-inline:10px;color:white}\n/*# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoibmV3dGFiLnN2ZWx0ZSIsInNvdXJjZXMiOlsibmV3dGFiLnN2ZWx0ZSJdLCJzb3VyY2VzQ29udGVudCI6WyI8c3R5bGU+XHJcbiAgLmFwcCB7XHJcbiAgICBwb3NpdGlvbjogZml4ZWQ7XHJcbiAgICB3aWR0aDogMTAwJTtcclxuICAgIGhlaWdodDogMTAwJTtcclxuICAgIGJhY2tkcm9wLWZpbHRlcjogYmx1cigzcHgpO1xyXG4gIH1cclxuICBoMiB7XHJcbiAgICBtYXJnaW4taW5saW5lOiAxMHB4O1xyXG4gICAgY29sb3I6IHdoaXRlO1xyXG4gIH1cclxuPC9zdHlsZT5cclxuXHJcbjxzY3JpcHQ+XHJcbjwvc2NyaXB0PlxyXG5cclxuPGRpdiBjbGFzcz1cImFwcFwiPlxyXG4gIDxoMj5UaGlzIGlzIGEgbmV3IHRhYi48L2gyPlxyXG48L2Rpdj4iXSwibmFtZXMiOltdLCJtYXBwaW5ncyI6IkFBQ0UsSUFBSSxlQUFDLENBQUMsQUFDSixRQUFRLENBQUUsS0FBSyxDQUNmLEtBQUssQ0FBRSxJQUFJLENBQ1gsTUFBTSxDQUFFLElBQUksQ0FDWixlQUFlLENBQUUsS0FBSyxHQUFHLENBQUMsQUFDNUIsQ0FBQyxBQUNELEVBQUUsZUFBQyxDQUFDLEFBQ0YsYUFBYSxDQUFFLElBQUksQ0FDbkIsS0FBSyxDQUFFLEtBQUssQUFDZCxDQUFDIn0= */");
}

function create_fragment(ctx) {
	let div;
	let h2;

	const block = {
		c: function create() {
			div = element("div");
			h2 = element("h2");
			h2.textContent = "This is a new tab.";
			attr_dev(h2, "class", "svelte-1wkv2w3");
			add_location(h2, file, 17, 2, 230);
			attr_dev(div, "class", "app svelte-1wkv2w3");
			add_location(div, file, 16, 0, 209);
		},
		l: function claim(nodes) {
			throw new Error("options.hydrate only works if the component was compiled with the `hydratable: true` option");
		},
		m: function mount(target, anchor) {
			insert_dev(target, div, anchor);
			append_dev(div, h2);
		},
		p: noop,
		i: noop,
		o: noop,
		d: function destroy(detaching) {
			if (detaching) detach_dev(div);
		}
	};

	dispatch_dev("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props) {
	let { $$slots: slots = {}, $$scope } = $$props;
	validate_slots('Newtab', slots, []);
	const writable_props = [];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== '$$' && key !== 'slot') console.warn(`<Newtab> was created with unknown prop '${key}'`);
	});

	return [];
}

class Newtab extends SvelteComponentDev {
	constructor(options) {
		super(options);
		init(this, options, instance, create_fragment, safe_not_equal, {}, add_css);

		dispatch_dev("SvelteRegisterComponent", {
			component: this,
			tagName: "Newtab",
			options,
			id: create_fragment.name
		});
	}
}

export default Newtab;