/* ArrowFwd.svelte generated by Svelte v3.48.0 */
import {
	SvelteComponentDev,
	add_location,
	append_dev,
	attr_dev,
	detach_dev,
	dispatch_dev,
	init,
	insert_dev,
	noop,
	safe_not_equal,
	svg_element,
	validate_slots
} from "nereid://.svelte/internal/index.mjs";

const file = "ArrowFwd.svelte";

function create_fragment(ctx) {
	let svg;
	let g0;
	let path;
	let g1;
	let polygon;

	const block = {
		c: function create() {
			svg = svg_element("svg");
			g0 = svg_element("g");
			path = svg_element("path");
			g1 = svg_element("g");
			polygon = svg_element("polygon");
			attr_dev(path, "d", "M0,0h24v24H0V0z");
			attr_dev(path, "fill", "none");
			add_location(path, file, 5, 5, 250);
			add_location(g0, file, 5, 2, 247);
			attr_dev(polygon, "points", "6.23,20.23 8,22 18,12 8,2 6.23,3.77 14.46,12");
			add_location(polygon, file, 6, 5, 300);
			add_location(g1, file, 6, 2, 297);
			attr_dev(svg, "title", /*title*/ ctx[0]);
			attr_dev(svg, "xmlns", "http://www.w3.org/2000/svg");
			attr_dev(svg, "enable-background", "new 0 0 24 24");
			attr_dev(svg, "height", "24px");
			attr_dev(svg, "viewBox", "0 0 24 24");
			attr_dev(svg, "width", "24px");
			attr_dev(svg, "fill", "var(--fds-text-primary)");
			add_location(svg, file, 4, 0, 83);
		},
		l: function claim(nodes) {
			throw new Error("options.hydrate only works if the component was compiled with the `hydratable: true` option");
		},
		m: function mount(target, anchor) {
			insert_dev(target, svg, anchor);
			append_dev(svg, g0);
			append_dev(g0, path);
			append_dev(svg, g1);
			append_dev(g1, polygon);
		},
		p: function update(ctx, [dirty]) {
			if (dirty & /*title*/ 1) {
				attr_dev(svg, "title", /*title*/ ctx[0]);
			}
		},
		i: noop,
		o: noop,
		d: function destroy(detaching) {
			if (detaching) detach_dev(svg);
		}
	};

	dispatch_dev("SvelteRegisterBlock", {
		block,
		id: create_fragment.name,
		type: "component",
		source: "",
		ctx
	});

	return block;
}

function instance($$self, $$props, $$invalidate) {
	let { $$slots: slots = {}, $$scope } = $$props;
	validate_slots('ArrowFwd', slots, []);
	let { title = "" } = $$props;
	const writable_props = ['title'];

	Object.keys($$props).forEach(key => {
		if (!~writable_props.indexOf(key) && key.slice(0, 2) !== '$$' && key !== 'slot') console.warn(`<ArrowFwd> was created with unknown prop '${key}'`);
	});

	$$self.$$set = $$props => {
		if ('title' in $$props) $$invalidate(0, title = $$props.title);
	};

	$$self.$capture_state = () => ({ title });

	$$self.$inject_state = $$props => {
		if ('title' in $$props) $$invalidate(0, title = $$props.title);
	};

	if ($$props && "$$inject" in $$props) {
		$$self.$inject_state($$props.$$inject);
	}

	return [title];
}

class ArrowFwd extends SvelteComponentDev {
	constructor(options) {
		super(options);
		init(this, options, instance, create_fragment, safe_not_equal, { title: 0 });

		dispatch_dev("SvelteRegisterComponent", {
			component: this,
			tagName: "ArrowFwd",
			options,
			id: create_fragment.name
		});
	}

	get title() {
		throw new Error("<ArrowFwd>: Props cannot be read directly from the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}

	set title(value) {
		throw new Error("<ArrowFwd>: Props cannot be set directly on the component instance unless compiling with 'accessors: true' or '<svelte:options accessors/>'");
	}
}

export default ArrowFwd;