export { default as ArrowBack } from "./icons/ArrowBack.svelte"
export { default as ArrowFwd } from "./icons/ArrowFwd.svelte"
export { default as Delete } from "./icons/Delete.svelte"
export { default as Edit } from "./icons/Edit.svelte"
export { default as Add } from "./icons/Add.svelte"
export { default as Close } from "./icons/Close.svelte"
export { default as More } from "./icons/More.svelte"

export { default as Settings } from "./icons/Settings.svelte"
export { default as History } from "./icons/History.svelte"
export { default as Bookmarks } from "./icons/Bookmarks.svelte"
export { default as Downloads } from "./icons/Downloads.svelte"
export { default as About } from "./icons/About.svelte"